import React, { useState, useEffect } from "react";
import AdminLayout from "@/layouts/AdminLayout";
import Head from "next/head";
import DataTable from "react-data-table-component";
import InputGroup from "react-bootstrap/InputGroup";
import Form from "react-bootstrap/Form";
import Image from "next/image";
import Button from "react-bootstrap/Button";
import Login from '../components/OTPLogin';

const columns = [
  {
    name: "Title",
    selector: (row) => row.title,
  },
  {
    name: "Year",
    selector: (row) => row.year,
  },
];

const data = [
  {
    id: 1,
    title: "Beetlejuice",
    year: "1988",
  },
  {
    id: 2,
    title: "Ghostbusters",
    year: "1984",
  },
];

export default function Dashboard() {
  const [domLoaded, setDomLoaded] = useState(false);
  useEffect(() => {
    setDomLoaded(true);
  }, []);
  return (
    <div>
      <Head>
        <title>Occupations</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AdminLayout>
        <div className="row toolbar">
          <div className="col-lg-4">
            <InputGroup className="mb-3 ms-3">
              <InputGroup.Text id="basic-addon1">
                <Image
                  src="/images/icons/search-icon.svg"
                  width="18"
                  height="18"
                  alt=""
                ></Image>
              </InputGroup.Text>
              <Form.Control
                placeholder="Search"
                aria-label="search"
                aria-describedby="basic-addon1"
              />
            </InputGroup>
          </div>
          <div className="col-lg-8 d-flex justify-content-end">
            <Button variant="primary me-4 "> + Create New</Button>
          </div>
        </div>
        {domLoaded ? (
          <DataTable columns={columns} data={data} pagination />
        ) : (
          ""
        )}
      </AdminLayout>
    </div>
  );
}
